apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kolab-aja-be
  namespace: argocd
spec:
  project: default
  replicas: 1
  source:
    repoURL: https://github.com/kolab-aja/kolab_aja_argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: kolabajabe

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true