apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolabajabe
spec:
  selector:
    matchLabels:
      app: kolabajabe
  template:
    metadata:
      labels:
        app: kolabajabe
    spec:
      containers:
        - name: kolabajabe
          image: edbfort/kolab-aja-be:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: myapp-service.kolabajamysql.svc.cluster.local  # Update with your database host (e.g., MySQL host or Docker container IP)
            - name: DB_PORT
              value: "3306"  # Replace with the correct port (default MySQL port is 3306)
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: ""        # The key inside the secret
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


