apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolabajabe
spec:
  selector:
    matchLabels:
      app: kolabajabe
  replicas: 3
  template:
    metadata:
      labels:
        app: kolabajabe
    spec:
      containers:
        - name: kolabajabe
          image: edbfort/kolab-aja-be:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "192.168.59.1"  # Update with your database host (e.g., MySQL host or Docker container IP)
            - name: DB_PORT
              value: "3306"  # Replace with the correct port (default MySQL port is 3306)
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # The secret you created
                  key: username         # The key inside the secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # The secret you created
                  key: password         # The key inside the secret
