apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kolabajabe-hpa
  namespace: kolabajabe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kolabajabe
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
