apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: kolabajabe
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"  # Enable CORS
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://myapp-service.kolabajafe.svc.cluster.local:3000"  # Frontend URL
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE"  # Allowed methods
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type,Authorization"  # Allowed headers
spec:
  rules:
  - host: myapp-service.kolabajabe.svc.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-service
            port:
              number: 8000
