apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-rolebinding
  namespace: kolabajabe
subjects:
- kind: ServiceAccount
  name: default
  namespace: kolabajabe
roleRef:
  kind: Role
  name: port-forward-role
  apiGroup: rbac.authorization.k8s.io
