apiVersion: v1
kind: Service
metadata:
  name: myapp-service-local
spec:
  selector:
    app: kolabajabe
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  type: NodePort
  
